application: keep-tabs-on
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/static_html/index.html
  upload: static/(.*\.(gif|png|jpg))

- url: /(.*)
  script: KeepTabsOn.application

- url: /css
  static_dir: static/stylesheets

- url: /js
  static_dir: static/javascript

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest