application: gcdc2013-keeptabson
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/static_html/index.html
  upload: static/static_html/index.html

- url: /css
  mime_type: text/css
  static_dir: static/stylesheets

- url: /js
  mime_type: text/javascript
  static_dir: static/javascript

- url: /(.+)
  script: KeepTabsOn.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest